# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drz/Program/ls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drz/Program/ls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drz/Program/ls/CMakeFiles /home/drz/Program/ls/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drz/Program/ls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lsmalloc_static

# Build rule for target.
lsmalloc_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsmalloc_static
.PHONY : lsmalloc_static

# fast build rule for target.
lsmalloc_static/fast:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/build
.PHONY : lsmalloc_static/fast

src/arena.o: src/arena.c.o

.PHONY : src/arena.o

# target to build an object file
src/arena.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/arena.c.o
.PHONY : src/arena.c.o

src/arena.i: src/arena.c.i

.PHONY : src/arena.i

# target to preprocess a source file
src/arena.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/arena.c.i
.PHONY : src/arena.c.i

src/arena.s: src/arena.c.s

.PHONY : src/arena.s

# target to generate assembly for a file
src/arena.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/arena.c.s
.PHONY : src/arena.c.s

src/base.o: src/base.c.o

.PHONY : src/base.o

# target to build an object file
src/base.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/base.c.o
.PHONY : src/base.c.o

src/base.i: src/base.c.i

.PHONY : src/base.i

# target to preprocess a source file
src/base.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/base.c.i
.PHONY : src/base.c.i

src/base.s: src/base.c.s

.PHONY : src/base.s

# target to generate assembly for a file
src/base.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/base.c.s
.PHONY : src/base.c.s

src/chunk.o: src/chunk.c.o

.PHONY : src/chunk.o

# target to build an object file
src/chunk.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/chunk.c.o
.PHONY : src/chunk.c.o

src/chunk.i: src/chunk.c.i

.PHONY : src/chunk.i

# target to preprocess a source file
src/chunk.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/chunk.c.i
.PHONY : src/chunk.c.i

src/chunk.s: src/chunk.c.s

.PHONY : src/chunk.s

# target to generate assembly for a file
src/chunk.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/chunk.c.s
.PHONY : src/chunk.c.s

src/chunk_mmap.o: src/chunk_mmap.c.o

.PHONY : src/chunk_mmap.o

# target to build an object file
src/chunk_mmap.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/chunk_mmap.c.o
.PHONY : src/chunk_mmap.c.o

src/chunk_mmap.i: src/chunk_mmap.c.i

.PHONY : src/chunk_mmap.i

# target to preprocess a source file
src/chunk_mmap.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/chunk_mmap.c.i
.PHONY : src/chunk_mmap.c.i

src/chunk_mmap.s: src/chunk_mmap.c.s

.PHONY : src/chunk_mmap.s

# target to generate assembly for a file
src/chunk_mmap.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/chunk_mmap.c.s
.PHONY : src/chunk_mmap.c.s

src/huge.o: src/huge.c.o

.PHONY : src/huge.o

# target to build an object file
src/huge.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/huge.c.o
.PHONY : src/huge.c.o

src/huge.i: src/huge.c.i

.PHONY : src/huge.i

# target to preprocess a source file
src/huge.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/huge.c.i
.PHONY : src/huge.c.i

src/huge.s: src/huge.c.s

.PHONY : src/huge.s

# target to generate assembly for a file
src/huge.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/huge.c.s
.PHONY : src/huge.c.s

src/lsmalloc.o: src/lsmalloc.c.o

.PHONY : src/lsmalloc.o

# target to build an object file
src/lsmalloc.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/lsmalloc.c.o
.PHONY : src/lsmalloc.c.o

src/lsmalloc.i: src/lsmalloc.c.i

.PHONY : src/lsmalloc.i

# target to preprocess a source file
src/lsmalloc.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/lsmalloc.c.i
.PHONY : src/lsmalloc.c.i

src/lsmalloc.s: src/lsmalloc.c.s

.PHONY : src/lsmalloc.s

# target to generate assembly for a file
src/lsmalloc.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/lsmalloc.c.s
.PHONY : src/lsmalloc.c.s

src/mutex.o: src/mutex.c.o

.PHONY : src/mutex.o

# target to build an object file
src/mutex.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/mutex.c.o
.PHONY : src/mutex.c.o

src/mutex.i: src/mutex.c.i

.PHONY : src/mutex.i

# target to preprocess a source file
src/mutex.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/mutex.c.i
.PHONY : src/mutex.c.i

src/mutex.s: src/mutex.c.s

.PHONY : src/mutex.s

# target to generate assembly for a file
src/mutex.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/mutex.c.s
.PHONY : src/mutex.c.s

src/pool.o: src/pool.c.o

.PHONY : src/pool.o

# target to build an object file
src/pool.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/pool.c.o
.PHONY : src/pool.c.o

src/pool.i: src/pool.c.i

.PHONY : src/pool.i

# target to preprocess a source file
src/pool.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/pool.c.i
.PHONY : src/pool.c.i

src/pool.s: src/pool.c.s

.PHONY : src/pool.s

# target to generate assembly for a file
src/pool.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/pool.c.s
.PHONY : src/pool.c.s

src/template.o: src/template.c.o

.PHONY : src/template.o

# target to build an object file
src/template.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/template.c.o
.PHONY : src/template.c.o

src/template.i: src/template.c.i

.PHONY : src/template.i

# target to preprocess a source file
src/template.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/template.c.i
.PHONY : src/template.c.i

src/template.s: src/template.c.s

.PHONY : src/template.s

# target to generate assembly for a file
src/template.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/template.c.s
.PHONY : src/template.c.s

src/tsd.o: src/tsd.c.o

.PHONY : src/tsd.o

# target to build an object file
src/tsd.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/tsd.c.o
.PHONY : src/tsd.c.o

src/tsd.i: src/tsd.c.i

.PHONY : src/tsd.i

# target to preprocess a source file
src/tsd.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/tsd.c.i
.PHONY : src/tsd.c.i

src/tsd.s: src/tsd.c.s

.PHONY : src/tsd.s

# target to generate assembly for a file
src/tsd.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/tsd.c.s
.PHONY : src/tsd.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/lsmalloc_static.dir/build.make CMakeFiles/lsmalloc_static.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lsmalloc_static"
	@echo "... edit_cache"
	@echo "... src/arena.o"
	@echo "... src/arena.i"
	@echo "... src/arena.s"
	@echo "... src/base.o"
	@echo "... src/base.i"
	@echo "... src/base.s"
	@echo "... src/chunk.o"
	@echo "... src/chunk.i"
	@echo "... src/chunk.s"
	@echo "... src/chunk_mmap.o"
	@echo "... src/chunk_mmap.i"
	@echo "... src/chunk_mmap.s"
	@echo "... src/huge.o"
	@echo "... src/huge.i"
	@echo "... src/huge.s"
	@echo "... src/lsmalloc.o"
	@echo "... src/lsmalloc.i"
	@echo "... src/lsmalloc.s"
	@echo "... src/mutex.o"
	@echo "... src/mutex.i"
	@echo "... src/mutex.s"
	@echo "... src/pool.o"
	@echo "... src/pool.i"
	@echo "... src/pool.s"
	@echo "... src/template.o"
	@echo "... src/template.i"
	@echo "... src/template.s"
	@echo "... src/tsd.o"
	@echo "... src/tsd.i"
	@echo "... src/tsd.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

